tablenames = ['ANNULUS', 'ANN_SECT', 'AVAILABLE_CONVERSION',
                'BHA_COMPONENT', 'BHA_DRILLING_PARAMETERS', 'BHA_RUN',
                'BIT_CONDITION', 'BIT_JETS', 'BLOCK', 'BLOCK_TO_OBJECT',
                'CAT_FLUID_PRODUCTS', 'CAT_PUMP', 'COMPANY_NAME', 'CSG',
                'DAILY_REPORT', 'DBIT', 'DRILLCOLLAR', 'DRILLPIPE',
                'FACILITY_TAB', 'FLOAT_COLLAR', 'FLOAT_SHOE',
                'FLUID_CHECKS', 'FLUID_DISPOSAL_METHOD', 'FLUID_HSE',
                'FLUID_HYDRAULICS', 'FLUID_IADC_HOUR', 'FLUID_INTERVAL',
                'FLUID_INV', 'FLUID_MGT', 'FLUID_MUD_SPECIFICATION',
                'FLUID_PITS', 'FLUID_PLIST', 'FLUID_PRODUCTS_INV',
                'FLUID_PUMP_STATUS', 'FLUID_SOLIDS', 'FLUID_SPEC_GRAVITIES',
                'FLUID_VOLUMES', 'HEAVYWT', 'JARS', 'MODEL_DOC', 'MOTOR',
                'MUD_EQUIPMENT', 'MUD_REPORT', 'MWD_TOOL',
                'OBJECT_OF_INTEREST_TAB', 'OBJECT_TO_FACILITY',
                'OBJECT_TO_WELL', 'PATH', 'PATH_TO_WELLBORE', 'PROGRAM_TAB',
                'PROGRAM_TO_WELLBORE', 'REF_AREA', 'REF_CASING_PURPOSE',
                'REF_COUNTRY', 'REF_FLUID_NAME', 'REF_FORMATION',
                'REF_INTEQ_TITLE', 'REF_LITHOLOGY', 'REF_MUD_TYPE',
                'REF_RIGLINK3_GROUP', 'REF_RIGLINK_GROUP', 'REF_STATE',
                'REPLICAUDIT', 'RIG', 'RIG_DATUM_HISTORY',
                'RIG_PIT_SPECIFICATION', 'RIG_PUMP', 'RIG_SPECIFICATION',
                'SERVICES', 'SLOT', 'STABILIZER', 'UNIT_DESCRIPTION',
                'VALID_UNIT', 'WELLBORE', 'WELLBORE_DATA', 'WELL_TAB']


def getTableNames():
    return tablenames